[project]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "Mojoframe"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "<25"
pandas = ">=2.2.3,<3"
numojo = ">=0.5.0,<0.6"